repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
- repo: https://github.com/sqlfluff/sqlfluff
  rev: 1.3.2
  hooks:
    - id: sqlfluff-lint
